//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pub2xml.api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pub2xml.api.api.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying internal font styles....
        /// </summary>
        internal static string ApplyingInternalFontStyles {
            get {
                return ResourceManager.GetString("ApplyingInternalFontStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building shape.
        /// </summary>
        internal static string BuildingShape {
            get {
                return ResourceManager.GetString("BuildingShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating backup file....
        /// </summary>
        internal static string CreatingBackupFile {
            get {
                return ResourceManager.GetString("CreatingBackupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading publisher file....
        /// </summary>
        internal static string LoadingPublisherFile {
            get {
                return ResourceManager.GetString("LoadingPublisherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading XML file....
        /// </summary>
        internal static string LoadingXmlFile {
            get {
                return ResourceManager.GetString("LoadingXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing shape.
        /// </summary>
        internal static string ParsingShape {
            get {
                return ResourceManager.GetString("ParsingShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes....
        /// </summary>
        internal static string SavingChanges {
            get {
                return ResourceManager.GetString("SavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving image.
        /// </summary>
        internal static string SavingImage {
            get {
                return ResourceManager.GetString("SavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving output to XML file....
        /// </summary>
        internal static string SavingOutputToXmlFile {
            get {
                return ResourceManager.GetString("SavingOutputToXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving PDF file....
        /// </summary>
        internal static string SavingPDFFile {
            get {
                return ResourceManager.GetString("SavingPDFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving publisher file....
        /// </summary>
        internal static string SavingPublisherFile {
            get {
                return ResourceManager.GetString("SavingPublisherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table -&gt; Row.
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paragraph counts are different for shape id.
        /// </summary>
        internal static string TheParagraphCountsAreDifferentForShapeId {
            get {
                return ResourceManager.GetString("TheParagraphCountsAreDifferentForShapeId", resourceCulture);
            }
        }
    }
}
